"""
Test suite for Sliq Marketing website

Generated by AI Test Generator
Timestamp: 2025-01-02 19:16:20
"""

import pytest
from playwright.sync_api import Page, expect, TimeoutError

# Configure longer timeout for slow connections
TIMEOUT = 10000  # 10 seconds

def test_homepage_load(page: Page):
    """Test homepage loads successfully"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Verify key elements are visible
    expect(page.locator("img.h-24").first).to_be_visible(timeout=TIMEOUT)  # Logo
    expect(page.locator("nav.bg-background").first).to_be_visible(timeout=TIMEOUT)  # Navigation
    
    # Save screenshot
    page.screenshot(path="test-results/homepage_load.png")

def test_navigation_menu(page: Page):
    """Test main navigation menu"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Verify main menu items
    nav = page.locator("nav.bg-background").first
    expect(nav).to_be_visible(timeout=TIMEOUT)
    
    # Click on About link in navigation
    nav_about = page.get_by_role("navigation").get_by_role("link", name="About").first
    nav_about.wait_for(state="stable", timeout=TIMEOUT)
    nav_about.click(force=True)
    
    # Wait for navigation
    page.wait_for_url("**/about", timeout=TIMEOUT)
    
    # Save screenshot
    page.screenshot(path="test-results/navigation_menu.png")

def test_mobile_menu(page: Page):
    """Test mobile menu functionality"""
    # Set mobile viewport
    page.set_viewport_size({"width": 375, "height": 667})
    
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Click mobile menu button using specific role
    menu_button = page.get_by_role("button", name="Open main menu")
    expect(menu_button).to_be_visible(timeout=TIMEOUT)
    menu_button.click()
    
    # Verify mobile menu items are visible
    nav_links = page.locator("nav a").first
    expect(nav_links).to_be_visible(timeout=TIMEOUT)
    
    # Save screenshot
    page.screenshot(path="test-results/mobile_menu.png")

def test_services_links(page: Page):
    """Test services page navigation"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Click on Services link in navigation
    nav_services = page.locator("nav a:has-text('Services')").first
    nav_services.wait_for(state="stable", timeout=TIMEOUT)
    nav_services.click(force=True)
    
    # Wait for navigation
    page.wait_for_url("**/services", timeout=TIMEOUT)
    
    # Save screenshot
    page.screenshot(path="test-results/services_page.png")

def test_contact_navigation(page: Page):
    """Test contact page navigation"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Click on Contact link in navigation
    nav_contact = page.locator("nav a:has-text('Contact')").first
    nav_contact.wait_for(state="stable", timeout=TIMEOUT)
    nav_contact.click(force=True)
    
    # Wait for navigation
    page.wait_for_url("**/contact", timeout=TIMEOUT)
    
    # Save screenshot
    page.screenshot(path="test-results/contact_page.png")

def test_get_started_cta(page: Page):
    """Test Get Started CTA button"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Click on Get Started link using class and text
    get_started = page.locator("a.bg-primary:has-text('Get Started')").first
    get_started.wait_for(state="stable", timeout=TIMEOUT)
    get_started.click(force=True)
    
    # Wait for navigation
    page.wait_for_url("**/contact", timeout=TIMEOUT)
    
    # Save screenshot
    page.screenshot(path="test-results/get_started_cta.png")

def test_responsive_design(page: Page):
    """Test responsive design at different viewport sizes"""
    # Navigate to homepage
    page.goto("https://www.sliqmarketing.co.za/")
    
    # Wait for page load
    page.wait_for_load_state("networkidle")
    
    # Test mobile viewport
    page.set_viewport_size({"width": 375, "height": 667})
    menu_button = page.get_by_role("button", name="Open main menu")
    expect(menu_button).to_be_visible(timeout=TIMEOUT)
    page.screenshot(path="test-results/responsive_mobile.png")
    
    # Test tablet viewport
    page.set_viewport_size({"width": 768, "height": 1024})
    page.screenshot(path="test-results/responsive_tablet.png")
    
    # Test desktop viewport
    page.set_viewport_size({"width": 1280, "height": 720})
    nav = page.locator("nav.bg-background").first
    expect(nav).to_be_visible(timeout=TIMEOUT)
    page.screenshot(path="test-results/responsive_desktop.png")
